version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      - internal
    ports:
      - 15672:15672
      - 5672:5672

networks:
  internal:
    driver: bridge